server:
        bind:
                host: boundaries.nmwdi.internetofwater.dev
                port: 80
        url: https://boundaries.nmwdi.internetofwater.dev
        cors: true
        pretty_print: true
        language: en-US
        encoding: utf-8
        map: 
                url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
                attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
        limit: 10
logging:
        level: ERROR
  #logfile: /tmp/pygeoapi.log
metadata:
        identification:
                title: WDI PyGEOAPI Boundaries
                description: no description
                keywords:
                        - geospatial
                        - data
                        - api
                keywords_type: theme
                terms_of_service: https://creativecommons.org/licences/by/4.0/
                url: https://newmexicowaterdata.org
        license:
                name: CC-BY 4.0 license
                url: https://creativecommons.org/licenses/by/4.0/
        provider:
                name: NM WDI
                url: https://newmexicowaterdata.org
        contact:
                name: Ross, Jake
                position: Technical Lead
                address: 801 Leroy Place
                city: Socorro
                stateorprovince: New Mexico
                postalcode: 87801
                country: USA
                email: jake.ross@nmt.edu
                role: pointOfContact
resources:
        nm_st:
                type: collection
                title: NM State Boundary
                description: New Mexico Boundary (Census TIGER)
                keywords:
                        - boundaries
                links: 
                    - type: application/html
                      rel: canonical
                      title: geographic data source
                      href: https://catalog.newmexicowaterdata.org/dataset/nm-boundary
                      hreflang: en-US
                extents:
                        spatial:
                                bbox: [-180,-90,180,90]
                                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
                provider:
                        name: SQLiteGPKG
                        data: /data_out/st.gpkg
                        table: st
                        id_field: NAME00
                        uri_field: uri
                context:
                    - NAME00: https://schema.org/name
                    - about: https://schema.org/about
        nm_county:
                type: collection
                title: NM County Boundaries
                description: New Mexico County Boundaries 2018 (Census TIGER)
                keywords:
                        - boundaries
                links: 
                    - type: application/html
                      rel: canonical
                      title: geographic data source
                      href: https://catalog.newmexicowaterdata.org/dataset/new-mexico-county-boundary-2018
                      hreflang: en-US
                extents:
                        spatial:
                                bbox: [-180,-90,180,90]
                                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
                provider:
                        name: SQLiteGPKG
                        data: /data_out/county.gpkg
                        table: county
                        id_field: GEOID
                        uri_field: uri
                context:
                    - NAME: https://schema.org/name
        nm_place:
                type: collection
                title: NM Census Designated Places
                description: New Mexico Census Designated Places 2015 (Census TIGER)
                keywords:
                        - boundaries
                links: 
                    - type: application/html
                      rel: canonical
                      title: geographic data source
                      href: https://catalog.newmexicowaterdata.org/dataset/nm-cdps
                      hreflang: en-US
                extents:
                        spatial:
                                bbox: [-180,-90,180,90]
                                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
                provider:
                        name: SQLiteGPKG
                        data: /data_out/places.gpkg
                        table: places
                        id_field: GEOID
                        uri_field: uri
                context:
                    - NAME: https://schema.org/name
        nm_congress:
                type: collection
                title: NM US Congression Districts 2012-2020
                description: New Mexico Census Designated Places 2012-2020 
                keywords:
                        - boundaries
                links: 
                    - type: application/html
                      rel: canonical
                      title: geographic data source
                      href: https://catalog.newmexicowaterdata.org/dataset/new-mexico-congressional-districts
                      hreflang: en-US
                extents:
                        spatial:
                                bbox: [-180,-90,180,90]
                                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
                provider:
                        name: SQLiteGPKG
                        data: /data_out/congress.gpkg
                        table: congress
                        id_field: District_N
                context:
                    - Name: https://schema.org/name
        nm_huc8:
                type: collection
                title: NM HUC8
                description: New Mexico HUC 8 Boundaries
                keywords:
                        - boundaries
                links: 
                    - type: application/html
                      rel: canonical
                      title: geographic data source
                      href: https://catalog.newmexicowaterdata.org/dataset/nm-huc8
                      hreflang: en-US
                extents:
                        spatial:
                                bbox: [-180,-90,180,90]
                                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
                provider:
                        name: SQLiteGPKG
                        data: /data_out/huc8.gpkg
                        table: huc8
                        id_field: HUC8
                        uri_field: uri
                context:
                    - Name: https://schema.org/name
        nm_statehouse:
                type: collection
                title: NM State House 2012-2020 Boundaries
                description: New Mexico State House District Boundaries 2012-2020
                keywords:
                        - boundaries
                links: 
                    - type: application/html
                      rel: canonical
                      title: geographic data source
                      href: https://catalog.newmexicowaterdata.org/dataset/nm-house-boundaries
                      hreflang: en-US
                extents:
                        spatial:
                                bbox: [-180,-90,180,90]
                                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
                provider:
                        name: SQLiteGPKG
                        data: /data_out/sthouse.gpkg
                        table: sthouse
                        id_field: District_N
                context:
                    - FullName: https://schema.org/name
        nm_statesenate:
                type: collection
                title: NM State House 2012-2020 Boundaries
                description: New Mexico State Senate District Boundaries 2012-2020
                keywords:
                        - boundaries
                links: 
                    - type: application/html
                      rel: canonical
                      title: geographic data source
                      href: https://catalog.newmexicowaterdata.org/dataset/nm-senate-boundaries
                      hreflang: en-US
                extents:
                        spatial:
                                bbox: [-180,-90,180,90]
                                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
                provider:
                        name: SQLiteGPKG
                        data: /data_out/senate.gpkg
                        table: senate
                        id_field: District_N
                context:
                    - FullName: https://schema.org/name